- hosts: all
  sudo: yes
  roles:
    - { role: sshd, when: "ansible_os_family == 'RedHat'" }
    - { role: yum/epel, when: "ansible_os_family == 'RedHat'" }

- hosts: OSX
  roles:
    - { role: xcode,                                when: "ansible_os_family == 'Darwin'" }
    - { role: homebrew/install,                     when: "ansible_os_family == 'Darwin'" }
    - { role: homebrew/brew/cask,                   when: "ansible_os_family == 'Darwin'" }
    - { role: homebrew/brew/wget,                   when: "ansible_os_family == 'Darwin'" }
    - { role: homebrew/brew/git,                    when: "ansible_os_family == 'Darwin'" }
    - { role: homebrew/brew/packer,                 when: "ansible_os_family == 'Darwin'" }
    - { role: homebrew/cask/virtualbox,             when: "ansible_os_family == 'Darwin'" }
    - { role: homebrew/cask/vagrant,                when: "ansible_os_family == 'Darwin'" }
    - { role: vagrant/plugins/vagrant-vbguest }
    - { role: vagrant/plugins/sahara }
    - { role: packer/build/virtualbox/centos6.4-x86 }
    - { role: vagrant/up-provision/setup }

- hosts: LOCAL
  sudo: yes
  roles:
    - { role: yum/remi }
    - { role: yum/rpmforge }
    - { role: resolv }
    - { role: vim-enhanced/install }
    - { role: vim-enhanced/plugins/neobundle }
    - { role: vim-enhanced/dotfiles }
    - { role: ruby/rbenv }
    - { role: ruby/ruby-build }
    - { role: ruby/ruby-binstubs }
    - { role: ruby/rbenv-gem-rehash }
    - { role: ruby/gem/bundle }
    - { role: ruby/bundle }
    - { role: ruby/gem/rails }
    - { role: git }
    - { role: java/openjdk }
    - { role: jenkins/install }
    - { role: jenkins/plugins/rbenv }
    - { role: jenkins/plugins/yammer }
    - { role: jenkins/plugins/build-with-parameters }
    - { role: jenkins/plugins/extended-choice-parameter }
    - { role: python/pyenv }
    - { role: nodejs/ndenv }
    - { role: nodejs/node-build }
    - { role: nodejs/npm/hubot }
    - { role: redis/install }
    - { role: pngquant/install }
    - { role: mysql/install }
- hosts: VAGRANT_LOCAL
  sudo: yes
  roles:
    - { role: yum/remi }
    - { role: yum/rpmforge }
    - { role: resolv }
    - { role: vim-enhanced/install }
    - { role: vim-enhanced/plugins/neobundle }
    - { role: vim-enhanced/dotfiles }
    - { role: ruby/rbenv }
    - { role: ruby/ruby-build }
    - { role: ruby/ruby-binstubs }
    - { role: ruby/rbenv-gem-rehash }
    - { role: ruby/gem/bundle }
    - { role: ruby/bundle }
    - { role: ruby/gem/rails }
    - { role: git }
    - { role: java/openjdk }
    - { role: jenkins/install }
    - { role: jenkins/plugins/rbenv }
    - { role: jenkins/plugins/yammer }
    - { role: jenkins/plugins/build-with-parameters }
    - { role: jenkins/plugins/extended-choice-parameter }
    - { role: python/pyenv }
    - { role: nodejs/ndenv }
    - { role: nodejs/node-build }
    - { role: nodejs/npm/hubot }
    - { role: redis/install }
    - { role: pngquant/install }
    - { role: mysql/install }
